# Generated by Django 3.2.23 on 2024-02-20 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_user_userprofile_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='userprofile',
            new_name='user',
        ),
    ]
