# Generated by Django 3.2.23 on 2024-02-29 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_order', '0006_customorder_product_name'),
        ('checkout', '0005_auto_20240228_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='custom_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_order.customorder'),
        ),
    ]
