# Generated by Django 3.2.23 on 2024-02-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_order', '0002_customorder_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='product_id',
            field=models.IntegerField(default=1000),
        ),
    ]
