# Generated by Django 3.2.23 on 2024-02-26 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_order', '0003_customorder_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customorder',
            name='product_id',
        ),
    ]
