# Generated by Django 3.2.23 on 2024-02-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_order', '0005_customorder_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='product_name',
            field=models.CharField(default='Your Custom Order', max_length=80),
        ),
    ]
