# Generated by Django 3.2.23 on 2024-03-01 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_order', '0006_customorder_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customorder',
            name='user_profile',
        ),
    ]
